---
- hosts: localhost
  become: false
  tasks:
  - name: List  the script
    shell: ls -l /ansible
  - name: call python
    shell: /var/lib/awx/venv/awx/bin/python /ansible/updateBA.py
  - name: echo
    shell: echo '{{sys_id}}'
  
    
    
 
