---
- hosts: localhost
  become: false
  tasks:
  - name: List  the script
    shell: ls -l /ansible
  - name: call python
    shell: /var/lib/awx/venv/awx/bin/python /ansible/callServiceNow.py {{sys_id}} {{table}} {{description}}
  - name: Call IRE 
    shell: /var/lib/awx/venv/awx/bin/python /ansible/ireflow.py intranet Comments from Ansible Yaml file
  - name: Send an Event
    shell: /var/lib/awx/venv/awx/bin/python /ansible/eventAPI.py
  
    
    
 
