---
- hosts: all

  tasks:
    - name: Install Firewalld
      yum:
        name: firewalld
        state: latest
      become: yes
      
    - name: Install Ansible Python 2 Dependencies
      dnf:
        name: python-firewall
        state: present
      become: yes
