---
- hosts: localhost
  become: false
  tasks:
  - name: List  the script
    shell: ls -l /ansible
  - name: uname -a
    shell: uname -a
  - name: pwd
    shell: pwd
  - name: curl
    shell: curl --version
    
    
 
