---
- hosts: localhost
  become: false
  tasks:
  - name: List  the script
    shell: ls -l /ansible
  - name: uname -a
    shell: uname -a
  - name: call python
    shell: /var/lib/awx/venv/awx/bin/python /ansible/updateBA.py
  - name: curl
    shell: curl --version
    
    
 
