---
- hosts: all
  vars:
    ansible_host: "{{ vm_ip }}"
  vars_files:
    - vars/main.yml
    - vars.yaml
  roles:
    - role: geerlingguy.firewall
      become: yes
      become_method: sudo
  tasks:
    - name: enable http
      firewalld:
        service: https
        permanent: yes
        state: enabled
