---
- hosts: localhost
  # vars:
  #   ansible_host: "{{ vm_ip }}"
  vars_files:
    - vars/main.yml
    # - vars.yaml
  roles:
    - role: geerlingguy.firewall
  tasks:
    - name: enable http
      firewalld:
        service: https
        permanent: yes
        state: enabled
      become: yes
      become_user: root

