---
- hosts: all

  tasks:
    - name: Install Firewalld
      yum:
        name: firewalld
        state: latest
      become: yes
    
    - name: Install Ansible Python 2 Dependencies
      with_items:
      - python-firewall
      dnf:
        name: "{{item}}"
      state: present